### ISSUE TITLE
RuntimeError: Unable to switch USB devices now (Raspberry Pi Pico - v.1589  2020)

### ISSUE THREAD

**Issue by camzilla1050** [fasteddy516/CircuitPython_JoystickXL#41]
Hello,

I'm using a Raspberry Pico v.1589, installed  joystick_xl_0.4.3_cp9 and have issues executing boot.py:

> \>>> %Run -c $EDITOR_CONTENT
<function _get_device at 0x0x20010f00>
+++ Enabled JoystickXL 0.4.3 with 8 axes, 128 buttons and 4 hats for a total of 26 report bytes.
Traceback (appels les plus récents en dernier) :
  Fichier "<stdin>", ligne 15, dans <module>
RuntimeError: Unable to switch USB devices now
>>>  

at line 15 : create_js(axes=8, buttons=128, hats=4),

**Comment by fasteddy516** [comment]
I just tested joystick_xl_0.4.3 on a Raspberry Pi Pico 2W running CircuitPython 10.0.3 using the `boot.py` and `code.py` examples from `README.md` and everything worked fine.  Can you confirm the device you're running on, and the version of CircuitPython it is running?  The REPL output you posted doesn't look like what I would expect from CircuitPython.  (Note that joystick_xl will only work correctly in _CircuitPython_; if you're trying to use it in _MicroPython_ it will definitely not work.)

**Comment by fasteddy516** [comment]
> at line 15 : create_js(axes=8, buttons=128, hats=4),

Also, there is no `create_js()` function in joystick_xl - it's `create_joystick()`.

**Comment by camzilla1050** [comment]
Hi Eddy thanx for watch this,

`Adafruit CircuitPython 10.0.3 on 2025-10-17; Raspberry Pi Pico with rp2040
`
`joystick_xl.version: 0.4.3`

I tryed this on REPL
```
>>> joystick_xl.hid.create_joystick(axes=4, buttons=128, hats=4)
+++ Enabled JoystickXL 0.4.3 with 4 axes, 128 buttons and 4 hats for a total of 22 report bytes.
<Device>
```
but i guess there is no active device
```
>>> usb_hid.get_boot_device()
0
>>> 
```
```
>>> usb_hid.devices
(<Device>, <Device>, <Device>, <Device>)

```

**Comment by Mick3DIY** [comment]
Hi guys ! 

I reproduced the main README example and it works well with CircuitPython 10.0.x and JoystickXL 0.4.3_cp9 on a Raspberry Pi Pico v1 (via Thonny IDE).

Some infos from the `boot_out.txt` :
```
Adafruit CircuitPython 10.0.3 on 2025-10-17; Raspberry Pi Pico with rp2040
Board ID:raspberry_pi_pico
UID:xxxxx
boot.py output:
+ Enabled JoystickXL 0.4.3 with 2 axes, 2 buttons and 1 hats for a total of 4 report bytes.
```
@camzilla1050 Have you tried this simple example before anything else ?

**Comment by camzilla1050** [comment]
@Mick3DIY 

Hi , 

I realieze i tried the boot.py and code.py with latest CircuitPython version. Unfurtanly, it doesn't work with older version 10.0.x ... or less, same result running boot.py with Thonny  : 

```  
>>> %Run -c $EDITOR_CONTENT
+Enabled JoystickXL 0.4.3 with 2 axes, 2 buttons and 1 hats for a total of 4 report bytes. 
Traceback (most recent call last): 
  File "<stdin>", line 13, in <module>
RuntimeError: Cannot change USB devices now
```  

Running code.py:

```  
AttributeError: 'module' object has no attribute 'D9'
```  
But just changing button board.GPxx instead board.Dxx, seems works at this point.
No error message. 

Below Raspberry pico  i/o : 

``` 
help(board)

object <module 'board'> is of type module
  __name__ -- board
  board_id -- raspberry_pi_pico
  GP0 -- board.GP0
  GP1 -- board.GP1
  GP2 -- board.GP2
  GP3 -- board.GP3
  GP4 -- board.GP4
  GP5 -- board.GP5
  GP6 -- board.GP6
  GP7 -- board.GP7
  GP8 -- board.GP8
  GP9 -- board.GP9
  GP10 -- board.GP10
  GP11 -- board.GP11
  GP12 -- board.GP12
  GP13 -- board.GP13
  GP14 -- board.GP14
  GP15 -- board.GP15
  GP16 -- board.GP16
  GP17 -- board.GP17
  GP18 -- board.GP18
  GP19 -- board.GP19
  GP20 -- board.GP20
  GP21 -- board.GP21
  GP22 -- board.GP22
  SMPS_MODE -- board.SMPS_MODE
  GP23 -- board.SMPS_MODE
  VBUS_SENSE -- board.VBUS_SENSE
  GP24 -- board.VBUS_SENSE
  LED -- board.LED
  GP25 -- board.LED
  GP26_A0 -- board.GP26_A0
  GP26 -- board.GP26_A0
  A0 -- board.GP26_A0
  GP27_A1 -- board.GP27_A1
  GP27 -- board.GP27_A1
  A1 -- board.GP27_A1
  GP28_A2 -- board.GP28_A2
  GP28 -- board.GP28_A2
  A2 -- board.GP28_A2
  A3 -- board.A3
  VOLTAGE_MONITOR -- board.A3
  STEMMA_I2C -- <function>
```
